# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhereIs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhereIs
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SVProgressHUD'
  pod 'ActionSheetPicker-3.0'

  target 'WhereIsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WhereIsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
